version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - store_artifacts:
          path: ~/src/public
          prefix: public
      - run:
          name: pronto
          command: bundle
          when: always
